from distutils.core import setup
setup(
  name = 'vectors2d',
  packages = ['vectors2d'],
  version = 'beta',
  license='MIT',
  description = 'Small but useful module that allows the work with vectors in 2-dimensional space',
  author = 'Dmitry Popov',
  author_email = 'thedmitryp@ukr.net',
  url = 'https://github.com/MitryP/vectors',
  download_url = 'https://github.com/user/reponame/archive/v_01.tar.gz',
  keywords = ['vectors', '2-dimensional', 'flat', 'coordinates', 'open-source'],
  install_requires=[],
  classifiers=[
    'Development Status :: 4 - Beta',
    'Intended Audience :: Developers',
    'Topic :: Software Development :: Build Tools',
    'License :: OSI Approved :: MIT License',
    'Programming Language :: Python :: 3',
    'Programming Language :: Python :: 3.4',
    'Programming Language :: Python :: 3.5',
    'Programming Language :: Python :: 3.6',
    'Programming Language :: Python :: 3.7',
    'Programming Language :: Python :: 3.8',
  ],
)